---
- include: "rally.yml"
  when: inventory_hostname in groups['disco/rally']

- include: "influx.yml"
  when: inventory_hostname in groups['disco/influx']

- include: "logs.yml"

- include: "conf.yml"
