---
- name: Make a tar of the rally execution environment
  command: tar -czf /root/rally.tar.gz /root/rally_home

- name: Pull back the rally execution environment
  fetch: src=/root/rally.tar.gz
         dest={{ backup_dir }}/{{ inventory_hostname }}-rally.tar.gz
         flat=yes
