# -*- mode: ruby -*-
# vi: set ft=ruby :
#

machine = "xp-idle"

Vagrant.configure(2) do |config|
    # box isn't used
    config.vm.define "xp-idle" do |my|
      my.vm.box = "dummy"
    end

    # user to log with inside the vm
    config.ssh.username = "root"
    # password to use to log inside the vm 
    config.ssh.password = ""

    config.vm.provider "g5k" do |g5k|
      # user name used to connect to g5k
      g5k.username = "discovery"
      # private key 
      g5k.private_key = File.join(ENV['HOME'], ".ssh/id_rsa_discovery")
      # site to use
      g5k.site = "rennes"
      # image location 
      #g5k.image_location = "/grid5000/virt-images/alpine_docker.qcow2"
      # it could be backed by the ceph
      g5k.image_location = "rbd:discovery_kolla_registry/#{machine}:id=discovery:conf=/home/discovery/.ceph/config"
      g5k.backing_strategy = "snapshot"
      # ports to expose (at least ssh has to be forwarded)
      g5k.ports = ['2222-:22']
    end


     
end


